baseURL = "https://www.palaniraja.com/"
languageCode = "en-us"
title = "PR"
theme = "min"

copyright = "&copy; 2018 palaniraja"


publishDir = "docs"

# uglyURLs = true
canonifyURLs = true

paginate = 20

RSSLink = true
summaryLength = 20

[permalinks]
 projects = "projects/:title/"
 posts = "/:year/:month/:title/"



[[menu.main]]
  name = "Projects"
  weight = 1
  identifier = "projects"
  url = "/projects"


# [[menu.main]]
#   name = "Archives"
#   weight = 2
#   identifier = "archives"
#   url = "/archives"


[[menu.main]]
  name = "Blog"
  weight = 3
  identifier = "blog"
  url = "/posts"


[[menu.main]]
  name = "Archive"
  weight = 4
  identifier = "archive"
  url = "/archives"

[[menu.main]]
  name = "About"
  weight = 5
  identifier = "about"
  url = "/about"

[[menu.footer]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.footer]]
  name = "RSS"
  weight = 2
  identifier = "rss"
  url = "/index.xml"


[[menu.footer]]
  name = "Archive"
  weight = 3
  identifier = "Archive"
  url = "/archives/"

[[menu.footer]]
  name = "Categories"
  weight = 4
  identifier = "categories"
  url = "/categories/"

[[menu.footer]]
  name = "Tags"
  weight = 5
  identifier = "tags"
  url = "/tags/"

  
[[menu.footer]]
  name = "DevDiary"
  weight = 6
  identifier = "devdiary"
  url = "/devdiary/"




[[menu.footer]]
  name = "About"
  weight = 7
  identifier = "about"
  url = "/about/"

[params.author]
  name = "Palani Raja"

  # Gravatar or Abatar image
  #gravatar = "Gravatar email or MD5 Hash"
  #avatar = "/path/to/avatar"

  #instagram = "palaniraja"
  #tumblr = "qcfailed"
  #flickr = "palaniraja-mca"
  #linkedin = "palaniraja-p"
  #github = "palaniraja"
  #bitbucket = "palaniraja"
  #stackoverflow = "240255"
  #jsfiddle = "Jsfiddle username"
  #codepen = "Codepen username"



# [mediaTypes]
#     [mediaTypes."application/atom"]
#     suffixes = ["xml"]
# 
#     [outputFormats.Atom]
#     mediaType = "application/atom"
#     baseName = "index"
#     isPlainText = false

# [outputs]
#   home = [ "HTML", "Atom" ]
